/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.StateGovernment;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.VaccineRequestVCTS.VaccineRequestVCTS;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karan
 */
public class ManageVCenterDosesRequest extends javax.swing.JPanel {

    /**
     * Creates new form ManageCenterDosesRequest
     */
    UserAccount userAccount;
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public ManageVCenterDosesRequest(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        populateRequestTable();
        populateProcessTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblVCenterDosesRequest.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestVCTS vr : ecosystem.getRequestVCTSDirectory().getRequestVCTSDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(vr.getStateGovernment()) && vr.getVaccineRequestStatus().equalsIgnoreCase("Request Placed")){
               Object [] row = new Object[5];
               row[0] = vr;
               row[1] = vr.getVaccineManufacturer();
               row[2] = vr.getColdChainSupplier();
               row[3] = vr.getNumberOfDoses();
               row[4] = vr.getVaccineRequestStatus();
               dtm.addRow(row);
            }
        }
    }
    
    public void populateProcessTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblVCenterDosesProcess.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestVCTS vr : ecosystem.getRequestVCTSDirectory().getRequestVCTSDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(vr.getStateGovernment()) && vr.getVaccineRequestStatus().equalsIgnoreCase("Doses In Pipeline")){
               Object [] row = new Object[5];
               row[0] = vr;
               row[1] = vr.getVaccineManufacturer();
               row[2] = vr.getColdChainSupplier();
               row[3] = vr.getNumberOfDoses();
               row[4] = vr.getVaccineRequestStatus();
               dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblVCenterDosesRequest = new javax.swing.JTable();
        btnPipeline = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVCenterDosesProcess = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tblVCenterDosesRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Vaccine Center", "Cold Chain", "Number of Doses", "Request Status"
            }
        ));
        jScrollPane3.setViewportView(tblVCenterDosesRequest);

        btnPipeline.setText("Order in Pipeline");
        btnPipeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPipelineActionPerformed(evt);
            }
        });

        tblVCenterDosesProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Vaccine Center", "Cold Chain", "Number of Doses", "Request Status"
            }
        ));
        jScrollPane2.setViewportView(tblVCenterDosesProcess);

        jLabel1.setText("Vaccination Center Doses Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnPipeline)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPipeline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPipelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPipelineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVCenterDosesRequest.getSelectedRow();
        VaccineRequestVCTS vr = (VaccineRequestVCTS)tblVCenterDosesRequest.getValueAt(selectedRow, 0);
        String status = "Doses In Pipeline";
        vr.setVaccineRequestStatus(status);
        populateProcessTable();
        populateRequestTable();
    }//GEN-LAST:event_btnPipelineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPipeline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblVCenterDosesProcess;
    private javax.swing.JTable tblVCenterDosesRequest;
    // End of variables declaration//GEN-END:variables
}
