/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.VaccinationSession;

import Business.AEFIManager.AEFIManager;
import Business.EcoSystem;
import Business.SessionManagers.SessionManager;
import Business.UserAccount.UserAccount;
import Business.VaccinationSession.VaccinationSession;
import Business.VaccinationSession.VaccinationSessionDirectory;
import Business.Vaccinator.Vaccinator;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Karan
 */
public class UpdateVaccinationSession extends javax.swing.JPanel {

    /**
     * Creates new form UpdateVaccinationSession
     */
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private VaccinationSessionDirectory vaccinationSessionDirectory;
    private VaccinationSession vaccinationSession;
    
    public UpdateVaccinationSession(UserAccount userAccount, JPanel userProcessContainer, EcoSystem ecosystem, VaccinationSessionDirectory vaccinationSessionDirectory, VaccinationSession vaccinationSession) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.vaccinationSessionDirectory = ecosystem.getVaccineSessionDirectory();
        this.vaccinationSession = vaccinationSession;
        txtName.setText(vaccinationSession.getSessionName());
        txtDate.setText(vaccinationSession.getSessionDate());
        txtStartTime.setText(String.valueOf(vaccinationSession.getStartTime()));
        txtEndTime.setText(String.valueOf(vaccinationSession.getEndTime()));
        sessionManagerCombo.setSelectedItem(vaccinationSession.getSessionManager());
        aefiManagerCombo.setSelectedItem(vaccinationSession.getAefiManager());
        vaccinatorComboBox.setSelectedItem(vaccinationSession.getVaccinator());
        vaccineComboBox.setSelectedItem(vaccinationSession.getVaccineName());
        txtAvailableDoses.setText(String.valueOf(vaccinationSession.getAvailableDoses()));
        selectSessionManager();
        selectAEFIManager();
        selectVaccinator();
    }
    
    public void selectSessionManager(){
        sessionManagerCombo.removeAllItems();
        sessionManagerCombo.addItem("Select Session Manager");
        for(SessionManager sm: ecosystem.getSessionManagerDirectory().getSessionManagerDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(sm.getCenterName())){
                sessionManagerCombo.addItem(sm.getManagerName());
            }
        }
   }
    
    public void selectAEFIManager(){
        aefiManagerCombo.removeAllItems();
        aefiManagerCombo.addItem("Select AEFI Manager");
        for(AEFIManager am: ecosystem.getAefiManagerDirectory().getAefiManagerDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(am.getCenterName())){
                aefiManagerCombo.addItem(am.getAefiManagerName());
            }
        }
   }
    
    public void selectVaccinator(){
        vaccinatorComboBox.removeAllItems();
        vaccinatorComboBox.addItem("Select Vaccinator");
        for(Vaccinator sm: ecosystem.getVaccinatorDirectory().getVaccinatorDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(sm.getCenterName())){
                vaccinatorComboBox.addItem(sm.getVaccinatorName());
            }
        }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        vaccinatorComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        vaccineComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAvailableDoses = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEndTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sessionManagerCombo = new javax.swing.JComboBox<>();
        aefiManagerCombo = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Name");

        vaccinatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Date");

        vaccineComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vaccine", "Pfizer", " " }));

        jLabel4.setText("startTime");

        jLabel5.setText("session manager");

        jLabel6.setText("end time");

        jLabel7.setText("aefi manager");

        jLabel8.setText("vaccinator");

        jLabel9.setText("vaccine");

        jLabel10.setText("available doses");

        sessionManagerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sessionManagerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionManagerComboActionPerformed(evt);
            }
        });

        aefiManagerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Update Vaccination Sessions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vaccinatorComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAvailableDoses, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStartTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEndTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sessionManagerCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aefiManagerCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaccineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sessionManagerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aefiManagerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vaccinatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(vaccineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAvailableDoses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnBack))
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sessionManagerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionManagerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionManagerComboActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String date = txtDate.getText();
        String stime = txtStartTime.getText();
        String etime = txtEndTime.getText();
        String smanager = sessionManagerCombo.getSelectedItem().toString();
        String amanager = aefiManagerCombo.getSelectedItem().toString();
        String vaccinator = vaccinatorComboBox.getSelectedItem().toString();
        String vaccine = vaccineComboBox.getSelectedItem().toString();
        String doses = txtAvailableDoses.getText();
        
        vaccinationSession.setSessionName(name);
        vaccinationSession.setSessionDate(date);
        vaccinationSession.setStartTime(Float.parseFloat(stime));
        vaccinationSession.setEndTime(Float.parseFloat(etime));
        vaccinationSession.setSessionManager(smanager);
        vaccinationSession.setAefiManager(amanager);
        vaccinationSession.setVaccinator(vaccinator);
        vaccinationSession.setVaccineName(vaccine);
        vaccinationSession.setAvailableDoses(Integer.parseInt(doses));

        JOptionPane.showMessageDialog(null, "Vaccination Session Updated");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAllSessions mavm = (ManageAllSessions) component;
        mavm.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aefiManagerCombo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> sessionManagerCombo;
    private javax.swing.JTextField txtAvailableDoses;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JComboBox<String> vaccinatorComboBox;
    private javax.swing.JComboBox<String> vaccineComboBox;
    // End of variables declaration//GEN-END:variables
}
