/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.ColdChainSupplier;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.VaccinationCenter.VaccinationCenter;
import Business.VaccineRequestVCTS.VaccineRequestVCTS;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karan
 */
public class ColdChainVCTS extends javax.swing.JPanel {

    /**
     * Creates new form ColdChainVCTS
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem; 
    UserAccount userAccount;
    public ColdChainVCTS(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = account;
        populateStateGovVaccineRequest();
    }
    
    public void populateStateGovVaccineRequest(){
        DefaultTableModel dtm = (DefaultTableModel) tblVaccinationCenterRequest.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestVCTS vr : ecosystem.getRequestVCTSDirectory().getRequestVCTSDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(vr.getColdChainSupplier()) && vr.getVaccineRequestStatus().equalsIgnoreCase("Doses In Pipeline")){
               Object [] row = new Object[5];
               row[0] = vr;
               row[1] = vr.getStateGovernment();
               row[2] = vr.getVaccinationCenter();
               row[3] = vr.getNumberOfDoses();
               row[4] = vr.getVaccineRequestStatus();
               dtm.addRow(row);
            }
        }
    }
    
    public void populateStateGovVaccineProcess(){
        DefaultTableModel dtm = (DefaultTableModel) tblVaccinationCenterProcess.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestVCTS vr : ecosystem.getRequestVCTSDirectory().getRequestVCTSDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(vr.getColdChainSupplier()) && vr.getVaccineRequestStatus().equalsIgnoreCase("Doses Delivered")){
               Object [] row = new Object[5];
               row[0] = vr;
               row[1] = vr.getStateGovernment();
               row[2] = vr.getVaccinationCenter();
               row[3] = vr.getNumberOfDoses();
               row[4] = vr.getVaccineRequestStatus();
               dtm.addRow(row);
            }
        }
    }
    
    public void adjustStockPlus(VaccineRequestVCTS vr){
        VaccinationCenter sg = ecosystem.getVaccinationCenterDirectory().getVaccinationCenter(vr.getVaccinationCenter());
        long updatedStock = sg.getCenterBalanceDoses() + vr.getNumberOfDoses();
        sg.setCenterBalanceDoses(updatedStock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblVaccinationCenterProcess = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVaccinationCenterRequest = new javax.swing.JTable();
        btnDelivered2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblVaccinationCenterProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "State Government", "Vaccination Center", "Number of Doses", "Request Status"
            }
        ));
        jScrollPane3.setViewportView(tblVaccinationCenterProcess);

        tblVaccinationCenterRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "State Government", "Vaccination Center", "Number of Doses", "Request Status"
            }
        ));
        jScrollPane4.setViewportView(tblVaccinationCenterRequest);

        btnDelivered2.setText("Delivered");
        btnDelivered2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelivered2ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelivered2)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelivered2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelivered2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelivered2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVaccinationCenterRequest.getSelectedRow();
        VaccineRequestVCTS vr = (VaccineRequestVCTS)tblVaccinationCenterRequest.getValueAt(selectedRow, 0);
        String status = "Doses Delivered";
        vr.setVaccineRequestStatus(status);
        adjustStockPlus(vr);
        populateStateGovVaccineProcess();
        populateStateGovVaccineRequest();
    }//GEN-LAST:event_btnDelivered2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelivered2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblVaccinationCenterProcess;
    private javax.swing.JTable tblVaccinationCenterRequest;
    // End of variables declaration//GEN-END:variables
}
