/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.ColdChainSupplier;

import Business.EcoSystem;
import Business.StateGovernment.StateGovernment;
import Business.UserAccount.UserAccount;
import Business.VaccineRequestSTF.VaccineRequestSTF;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karan
 */
public class ColdChainFTS extends javax.swing.JPanel {

    /**
     * Creates new form ColdChainFTS
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem; 
    UserAccount userAccount;
    public ColdChainFTS(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = account;
        populateStateGovVaccineRequest();
        populateStateGovVaccineProcess();
    }
    
    public void populateStateGovVaccineRequest(){
        DefaultTableModel dtm = (DefaultTableModel) tblStateGovernmentRequest.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestSTF vsr : ecosystem.getRequestSTFDirectory().getRequestSTFDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(vsr.getColdChainSupplier()) && vsr.getVaccineRequestStatus().equalsIgnoreCase("Doses In Pipeline")){
               Object [] row = new Object[6];
               row[0] = vsr;
               row[1] = vsr.getFedName();
               row[2] = vsr.getStateGovernment();
               row[3] = vsr.getNumberOfDoses();
               row[4] = vsr.getVaccineRequestStatus();
               row[5] = vsr.getFedName();
               dtm.addRow(row);
            }
        }
    }
    public void populateStateGovVaccineProcess(){
        DefaultTableModel dtm = (DefaultTableModel) tblStateGovernmentProcess.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestSTF vsr : ecosystem.getRequestSTFDirectory().getRequestSTFDirectory()){
            if(userAccount.getEmployee().getName().equalsIgnoreCase(vsr.getColdChainSupplier()) && vsr.getVaccineRequestStatus().equalsIgnoreCase("Doses Delivered")){
               Object [] row = new Object[6];
               row[0] = vsr;
               row[1] = vsr.getFedName();
               row[2] = vsr.getStateGovernment();
               row[3] = vsr.getNumberOfDoses();
               row[4] = vsr.getVaccineRequestStatus();
               row[5] = vsr.getFedName();
               dtm.addRow(row);
            }
        }
    }

    public void adjustStockPlus(VaccineRequestSTF vr){
        StateGovernment sg = ecosystem.getStateGovernmentDirectory().getStateGovernment(vr.getStateGovernment());
        long updatedStock = sg.getCurrentStock() + vr.getNumberOfDoses();
        sg.setCurrentStock(updatedStock);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblStateGovernmentProcess = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStateGovernmentRequest = new javax.swing.JTable();
        btnDelivered2 = new javax.swing.JButton();

        tblStateGovernmentProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Federal Government", "State Government", "Number of Doses", "Request Status", "Fed"
            }
        ));
        jScrollPane3.setViewportView(tblStateGovernmentProcess);

        tblStateGovernmentRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Federal Government", "State Government", "Number of Doses", "Request Status", "Fed"
            }
        ));
        jScrollPane4.setViewportView(tblStateGovernmentRequest);

        btnDelivered2.setText("Delivered");
        btnDelivered2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelivered2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelivered2))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelivered2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelivered2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelivered2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStateGovernmentRequest.getSelectedRow();
        VaccineRequestSTF vsr = (VaccineRequestSTF)tblStateGovernmentRequest.getValueAt(selectedRow, 0);
        String status = "Doses Delivered";
        vsr.setVaccineRequestStatus(status);
        adjustStockPlus(vsr);
        populateStateGovVaccineProcess();
        populateStateGovVaccineRequest();
    }//GEN-LAST:event_btnDelivered2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelivered2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblStateGovernmentProcess;
    private javax.swing.JTable tblStateGovernmentRequest;
    // End of variables declaration//GEN-END:variables
}
